#pragma once

#include "class/hid/hid.h"
#include "kb_matrix.h"
#include <stdint.h>

// special marker: falls back to default layer
#define KB_KEY_TRANSPARENT 0xFFFF

// Action Code Spaces
#define ACTION_CODE_NONE 0x0000

#define ACTION_CODE_HID_MIN 0x0001
#define ACTION_CODE_HID_MAX 0x00FF

#define ACTION_CODE_MEDIA_MIN 0x0100
#define ACTION_CODE_MEDIA_MAX 0x01FF

#define ACTION_CODE_SYSTEM_MIN 0x2000
#define ACTION_CODE_SYSTEM_MAX 0x20FF

#define ACTION_CODE_MACRO_MIN 0x4000
#define ACTION_CODE_MACRO_MAX 0x4FFF

// Specific System Actions
#define SYS_ACTION_LAYER_BASE (ACTION_CODE_SYSTEM_MIN + 0)
#define SYS_ACTION_LAYER_FN1 (ACTION_CODE_SYSTEM_MIN + 1)
#define SYS_ACTION_LAYER_FN2 (ACTION_CODE_SYSTEM_MIN + 2)

#define SYS_ACTION_BLE_ON     (ACTION_CODE_SYSTEM_MIN + 3)
#define SYS_ACTION_BLE_OFF    (ACTION_CODE_SYSTEM_MIN + 4)
#define SYS_ACTION_BLE_TOGGLE (ACTION_CODE_SYSTEM_MIN + 5)
#define SYS_ACTION_BLE_1      (ACTION_CODE_SYSTEM_MIN + 6)
#define SYS_ACTION_BLE_2      (ACTION_CODE_SYSTEM_MIN + 7)
#define SYS_ACTION_BLE_3      (ACTION_CODE_SYSTEM_MIN + 8)
#define SYS_ACTION_BLE_4      (ACTION_CODE_SYSTEM_MIN + 9)
#define SYS_ACTION_BLE_5      (ACTION_CODE_SYSTEM_MIN + 10)
#define SYS_ACTION_BLE_6      (ACTION_CODE_SYSTEM_MIN + 11)
#define SYS_ACTION_BLE_7      (ACTION_CODE_SYSTEM_MIN + 12)
#define SYS_ACTION_BLE_8      (ACTION_CODE_SYSTEM_MIN + 13)
#define SYS_ACTION_BLE_9      (ACTION_CODE_SYSTEM_MIN + 14)
#define SYS_ACTION_BLE_10     (ACTION_CODE_SYSTEM_MIN + 15)

#define SYS_ACTION_BRIGHTNESS_UP   (ACTION_CODE_SYSTEM_MIN + 16)
#define SYS_ACTION_BRIGHTNESS_DOWN (ACTION_CODE_SYSTEM_MIN + 17)

#define SYS_ACTION_VOLUME_UP   (ACTION_CODE_SYSTEM_MIN + 18)
#define SYS_ACTION_VOLUME_DOWN (ACTION_CODE_SYSTEM_MIN + 19)
#define SYS_ACTION_MUTE        (ACTION_CODE_SYSTEM_MIN + 20)

#define MEDIA_ACTION_NEXT   (ACTION_CODE_SYSTEM_MIN + 21)
#define MEDIA_ACTION_PREV   (ACTION_CODE_SYSTEM_MIN + 22)
#define MEDIA_ACTION_TOGGLE (ACTION_CODE_SYSTEM_MIN + 23)
#define MEDIA_ACTION_PLAY   MEDIA_ACTION_TOGGLE

#define SYS_ACTION_RGB_MODE_NEXT       (ACTION_CODE_SYSTEM_MIN + 24)
#define SYS_ACTION_RGB_MODE_PREV       (ACTION_CODE_SYSTEM_MIN + 25)
#define SYS_ACTION_RGB_SPEED_NEXT      (ACTION_CODE_SYSTEM_MIN + 26)
#define SYS_ACTION_RGB_SPEED_PREV      (ACTION_CODE_SYSTEM_MIN + 27)
#define SYS_ACTION_RGB_BRIGHTNESS_UP   (ACTION_CODE_SYSTEM_MIN + 28)
#define SYS_ACTION_RGB_BRIGHTNESS_DOWN (ACTION_CODE_SYSTEM_MIN + 29)

/*
    ================================================================================
    DEFAULT KEYBOARD LAYOUT
    ================================================================================
*/

#define KB_LAYER_COUNT 4
typedef enum {
  KB_LAYER_BASE = 0,
  KB_LAYER_FN1 = 1,
  KB_LAYER_FN2 = 2,
  KB_LAYER_FN3 = 3, // FN3 = FN1 + FN2
} kb_layer_t;

static const uint16_t
    keymaps[KB_LAYER_COUNT][KB_MATRIX_ROW_COUNT][KB_MATRIX_COL_COUNT] = {
        [KB_LAYER_BASE] =
        {   // Row 0
            {HID_KEY_ESCAPE, HID_KEY_1, HID_KEY_2, HID_KEY_3, HID_KEY_4, HID_KEY_5, HID_KEY_6, HID_KEY_7, HID_KEY_8, HID_KEY_9, HID_KEY_0, HID_KEY_MINUS, HID_KEY_EQUAL, HID_KEY_BACKSPACE, HID_KEY_INSERT},
            // Row 1
            {HID_KEY_TAB, HID_KEY_Q, HID_KEY_W, HID_KEY_E, HID_KEY_R, HID_KEY_T, HID_KEY_Y, HID_KEY_U, HID_KEY_I, HID_KEY_O, HID_KEY_P, HID_KEY_BRACKET_LEFT, HID_KEY_BRACKET_RIGHT, HID_KEY_BACKSLASH, HID_KEY_HOME},
            // Row 2
            {HID_KEY_CAPS_LOCK, HID_KEY_A, HID_KEY_S, HID_KEY_D, HID_KEY_F, HID_KEY_G, HID_KEY_H, HID_KEY_J, HID_KEY_K, HID_KEY_L, HID_KEY_SEMICOLON, HID_KEY_APOSTROPHE, HID_KEY_ENTER, HID_KEY_NONE, HID_KEY_PAGE_UP},
            // Row 3
            {HID_KEY_SHIFT_LEFT, HID_KEY_NONE, HID_KEY_Z, HID_KEY_X, HID_KEY_C, HID_KEY_V, HID_KEY_B, HID_KEY_N, HID_KEY_M, HID_KEY_COMMA, HID_KEY_PERIOD, HID_KEY_SLASH, HID_KEY_SHIFT_RIGHT, HID_KEY_ARROW_UP, HID_KEY_PAGE_DOWN},
            // Row 4
            {HID_KEY_CONTROL_LEFT, HID_KEY_GUI_LEFT, HID_KEY_ALT_LEFT, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_SPACE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_ALT_RIGHT, SYS_ACTION_LAYER_FN1, SYS_ACTION_LAYER_FN2, HID_KEY_ARROW_LEFT, HID_KEY_ARROW_DOWN, HID_KEY_ARROW_RIGHT}
        },

        [KB_LAYER_FN1] =
        {   // Row 0
            {HID_KEY_GRAVE, SYS_ACTION_BRIGHTNESS_DOWN, SYS_ACTION_BRIGHTNESS_UP, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, MEDIA_ACTION_PREV, MEDIA_ACTION_TOGGLE, MEDIA_ACTION_NEXT, SYS_ACTION_MUTE, SYS_ACTION_VOLUME_DOWN, SYS_ACTION_VOLUME_UP, KB_KEY_TRANSPARENT, HID_KEY_DELETE},
            // Row 1
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, HID_KEY_END},
            // Row 2
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 3
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 4
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, HID_KEY_MENU, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT}
        },

        [KB_LAYER_FN2] =
        {   // Row 0
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 1
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 2
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 3
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 4
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, HID_KEY_MENU, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT}
        },

        [KB_LAYER_FN3] =
        {   // Row 0
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 1
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 2
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 3
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT},
            // Row 4
            {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT}
        }
    };

uint16_t kb_layout_get_action_code(uint8_t row, uint8_t col, uint8_t layer);