#include "kb_layout.h"
#include "cfg_layouts.h"

/* ============================================================
   Factory-default keymap
   ============================================================
   Defining this here (not in the header) ensures a single copy in flash.
   cfg_layouts.c reads it via the extern declaration in kb_layout.h.
   ============================================================ */

const uint16_t keymaps[KB_LAYER_COUNT][KB_MATRIX_ROW_COUNT][KB_MATRIX_COL_COUNT] = {

    [KB_LAYER_BASE] = {
        // Row 0: Esc, 1-0, -, =, Backspace, Insert
        {HID_KEY_ESCAPE, HID_KEY_1, HID_KEY_2, HID_KEY_3, HID_KEY_4, HID_KEY_5,
         HID_KEY_6, HID_KEY_7, HID_KEY_8, HID_KEY_9, HID_KEY_0, HID_KEY_MINUS,
         HID_KEY_EQUAL, HID_KEY_BACKSPACE, HID_KEY_INSERT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 1: Tab, Q-P, [, ], \, Home
        {HID_KEY_TAB, HID_KEY_Q, HID_KEY_W, HID_KEY_E, HID_KEY_R, HID_KEY_T,
         HID_KEY_Y, HID_KEY_U, HID_KEY_I, HID_KEY_O, HID_KEY_P,
         HID_KEY_BRACKET_LEFT, HID_KEY_BRACKET_RIGHT, HID_KEY_BACKSLASH,
         HID_KEY_HOME, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 2: CapsLock, A-L, ;, ', Enter, PgUp
        {HID_KEY_CAPS_LOCK, HID_KEY_A, HID_KEY_S, HID_KEY_D, HID_KEY_F, HID_KEY_G,
         HID_KEY_H, HID_KEY_J, HID_KEY_K, HID_KEY_L, HID_KEY_SEMICOLON,
         HID_KEY_APOSTROPHE, HID_KEY_ENTER, HID_KEY_NONE,
         HID_KEY_PAGE_UP, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 3: LShift, Z-M, ,, ., /, RShift, Up, PgDn
        {HID_KEY_SHIFT_LEFT, HID_KEY_NONE, HID_KEY_Z, HID_KEY_X, HID_KEY_C,
         HID_KEY_V, HID_KEY_B, HID_KEY_N, HID_KEY_M, HID_KEY_COMMA,
         HID_KEY_PERIOD, HID_KEY_SLASH, HID_KEY_SHIFT_RIGHT,
         HID_KEY_ARROW_UP, HID_KEY_PAGE_DOWN, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 4: LCtrl, LGui, LAlt, Space, RAlt, FN1, FN2, Left, Down, Right
        {HID_KEY_CONTROL_LEFT, HID_KEY_GUI_LEFT, HID_KEY_ALT_LEFT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_SPACE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_ALT_RIGHT, SYS_ACTION_LAYER_FN1, SYS_ACTION_LAYER_FN2,
         HID_KEY_ARROW_LEFT, HID_KEY_ARROW_DOWN, HID_KEY_ARROW_RIGHT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 5: (unused)
        {HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
    },

    [KB_LAYER_FN1] = {
        // Row 0: `, Brightness, Media, Volume
        {HID_KEY_GRAVE, SYS_ACTION_BRIGHTNESS_DOWN, SYS_ACTION_BRIGHTNESS_UP,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         MEDIA_ACTION_PREV, MEDIA_ACTION_TOGGLE, MEDIA_ACTION_NEXT,
         SYS_ACTION_MUTE, SYS_ACTION_VOLUME_DOWN, SYS_ACTION_VOLUME_UP,
         KB_KEY_TRANSPARENT, HID_KEY_DELETE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 1: End key
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, HID_KEY_END,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Rows 2-3: transparent
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 4: Menu on AltRight position
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_MENU, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 5: (unused)
        {HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
    },

    [KB_LAYER_FN2] = {
        // Rows 0-3: transparent
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 4: Menu on AltRight position
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_MENU, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        // Row 5: (unused)
        {HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
    },

    [KB_LAYER_FN3] = {
        // All rows transparent (FN1+FN2 combo — customisable via configurator)
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT, KB_KEY_TRANSPARENT,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
        {HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE,
         HID_KEY_NONE, HID_KEY_NONE, HID_KEY_NONE},
    },
};

/* ============================================================
   Action code lookup (delegates to config module cache)
   ============================================================ */

uint16_t kb_layout_get_action_code(uint8_t row, uint8_t col, uint8_t layer) {
    return cfg_layout_get_action_code(row, col, layer);
}
